### ISSUE TITLE
No default configuration

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/markdown-proofing#16]
Currently there is no default configuration. Perhaps we could clean up this output, or provide a default configuration and note that it is being used.

```
λ npm t

> [redacted-package-name]@1.0.0 test C:\Users\[redacted_path]
> markdown-proofing _posts/*.md

C:\Users\[redacted_path]\node_modules\markdown-proofing\cli.js:59
  throw new Error('Configuration was not found or could not be read from \'' + filePath + '\'.', e);
  ^

Error: Configuration was not found or could not be read from 'C:\Users\[redacted_path]\.markdown-proofing'.
    at Object.<anonymous> (C:\Users\[redacted_path]\node_modules\markdown-proofing\cli.js:59:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
npm ERR! Test failed.  See above for more details.
```

**Comment by kendaleiv** [comment]
I think this might be OK, and a default configuration may not be a good idea. Closing.
